services:
  backend:
    build:
      context: ./backend
    container_name: easygenerator_backend_dev
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    env_file:
      - backend/.env
    environment:
      - NODE_ENV=development

  frontend:
    build:
      context: ./frontend
    container_name: easygenerator_frontend_dev
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
