services:
  app:
    build: .
    container_name: easygenerator_backend_dev
    restart: always
    ports:
      - "3333:3333"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - NODE_ENV=development

  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
